apiVersion: image.openshift.io/v1
kind: ImageStreamTag
metadata:
  name: go-sample:main
tag:
  from:
    kind: DockerImage
    name: quay.io/jfronius/go-sample:main
  importPolicy:
    scheduled: true
  referencePolicy:
    type: Source
